FROM arm32v7/node:12-alpine

RUN apk update && apk upgrade && \
    apk add --no-cache bash git openssh

COPY package.json package.json
COPY package-lock.json package-lock.json
COPY app.js app.js
COPY server.js server.js

RUN npm i --production

CMD npm start
